@startuml
skinparam actorBackgroundColor #darkblue
skinparam actorBorderColor #darkblue
left to right direction

actor professor

package "Criar atividade aberta" {
    usecase "Abrir Portal acadêmico" as CAA1
    usecase "Fazer login no sistema" as CAA2
    usecase "Selecionar painel do professor" as CAA3 
    usecase "Selecionar turma" as CAA4
    usecase "Selecionar opção atividades" as CAA5
    usecase "Selecionar opção criar atividade" as CAA6
    usecase "Selecionar atividade aberta" as CAA7
    usecase "Abrir editor de atividade" as CAA8
    usecase "Digitar descrição da atividade" as CAA9
    usecase "Selecionar quantidade de pontos" as CAA10
    usecase "Selecionar data de expiração" as CAA11
    usecase "Selecionar data de entrega" as CAA12
    usecase "Selecionar formato de arquivo" as CAA13
    usecase "Selecionar quantidade máxima de pessoas" as CAA14
    usecase "Salvar atividade" as CAA15
    usecase "Receber confirmação de criação" as CAA16

    usecase "Descriçâo com mais de 5000 caracteres" as ECAA9.1
    usecase "A descrição deve ter menos de 5000 caracteres" as ECAA9.2




}

professor -> CAA1
CAA1 -right.> CAA2 : <<include>>
CAA2 -right.> CAA3 : <<include>>
CAA3 -right.> CAA4 : <<include>>
CAA4 -right.> CAA5 : <<include>>
CAA5 -down.> CAA6 : <<include>>
CAA6 -right.> CAA7 : <<include>>
CAA7 -right.> CAA8 : <<include>>
CAA8 -.> CAA9  : <<include>>
CAA8 -.> CAA10 : <<include>>
CAA8 -.> CAA11 : <<include>>
CAA8 -.> CAA12 : <<include>>
CAA8 -.> CAA13 : <<include>>
CAA8 -.> CAA14 : <<include>>

ECAA9.1 -.> CAA9 : <<extends>>
ECAA9.1 -.> ECAA9.2 : <<include>>
ECAA9.2 -.> CAA9 : <<include>>

CAA9 -.> CAA15 : <<include>>
CAA10 -.> CAA15 : <<include>>
CAA11 -.> CAA15 : <<include>>
CAA12 -.> CAA15 : <<include>>
CAA13 -.> CAA15 : <<include>>
CAA14 -.> CAA15 : <<include>>


CAA15 -.> CAA16 : <<include>>
@enduml
